version: '3'

services:
  hadith-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3300:3300"    # Use the same port externally as internally
    environment:
      - NODE_ENV=production
      - PORT=3300
    volumes:
      - ./books:/app/books:ro
    restart: unless-stopped