version: '3'

services:
  hadith-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3300:3300"
    environment:
      - NODE_ENV=production
      - PORT=3300
    restart: unless-stopped