version: '3'

services:
  hadith-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:3300"    # Map container port 3300 to host port 80
    environment:
      - NODE_ENV=production
      - PORT=3300    # Keep internal port as 3300
    volumes:
      - type: bind
        source: ./books
        target: /app/books
    restart: unless-stopped