version: '3'

services:
  hadith-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3300:3300"    # Changed from 80:3300 to avoid port conflict
    environment:
      - NODE_ENV=production
      - PORT=3300    # Keep internal port as 3300
    volumes:
      - type: bind
        source: ./books
        target: /app/books
    restart: unless-stopped